FROM golang AS builder

WORKDIR /build

COPY . .

## Install dependencies
RUN echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
RUN apt update
RUN apt install goreleaser nodejs npm zip -y
RUN npm install yarn -g

## Build
RUN goreleaser build --single-target --clean --output cloudreve

FROM alpine:latest AS runner

WORKDIR /cloudreve
COPY --from=builder /build/cloudreve ./cloudreve

RUN apk update \
    && apk add --no-cache tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && chmod +x ./cloudreve \
    && mkdir -p /data/aria2 \
    && chmod -R 766 /data/aria2

EXPOSE 5212
VOLUME [ "/cloudreve/uploads", "/cloudreve/avatar", "/data" ]

ENTRYPOINT [ "./cloudreve" ]
