name: Docker Release

on:
  push:
    tags:
      - 3.* # triggered on every push with tag 3.*
  workflow_dispatch: # or just on button clicked

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU Emulator
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

#      - name: Login to Dockerhub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: cloudreve/cloudreve
          tags: |
            type=raw,value=latest
            type=ref,event=tag
      - name: Build Docker Image and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ steps.docker-metadata.outputs.tags }}
          context: .
          file: Dockerfile-Actions
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max
